// <auto-generated />
namespace Kibiriukas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReportingError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReportingError));
        
        string IMigrationMetadata.Id
        {
            get { return "201909101212289_ReportingError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
